USE Avior
DBCC FREEPROCCACHE WITH NO_INFOMSGS
GO

IF ( OBJECT_ID('dbo.SelectSerieReport') IS NOT NULL ) 
   DROP PROCEDURE dbo.SelectSerieReport
GO

CREATE PROCEDURE dbo.SelectSerieReport
	@IdReport INT = NULL
AS
BEGIN
	BEGIN TRY
	
			IF @IdReport IS NULL
				BEGIN
					SELECT * FROM dbo.SeriesReports WITH (NOLOCK)
				END
			ELSE
				BEGIN
					SELECT * FROM dbo.SeriesReports WITH (NOLOCK)
						WHERE IdReport = @IdReport	
				END	

	END TRY

	BEGIN CATCH

	SELECT ERROR_MESSAGE() AS ERROR,
				ERROR_NUMBER() AS ERROR_NRO

	END CATCH;
END
GO