USE Avior
DBCC FREEPROCCACHE WITH NO_INFOMSGS
GO

IF ( OBJECT_ID('dbo.DeleteReport') IS NOT NULL ) 
   DROP PROCEDURE dbo.DeleteReport
GO

CREATE PROCEDURE dbo.DeleteReport(
	@IdReport INT)
AS
BEGIN

SET NOCOUNT ON;

	BEGIN TRY
	
		IF EXISTS(SELECT IdReport 
						FROM dbo.Reports
						WHERE IdReport = @IdReport)
		BEGIN
			DELETE FROM dbo.Reports WHERE IdReport = @IdReport
		END

	END TRY

	BEGIN CATCH

	SELECT ERROR_MESSAGE() AS ERROR,
				ERROR_NUMBER() AS ERROR_NRO

	END CATCH;
END
GO