USE Avior
DBCC FREEPROCCACHE WITH NO_INFOMSGS
GO
IF ( OBJECT_ID('dbo.SelectReport') IS NOT NULL ) 
   DROP PROCEDURE dbo.SelectReport
GO
CREATE PROCEDURE dbo.SelectReport
	@IdReport INT = NULL,
	@StatusReport INT = NULL
AS
BEGIN
	BEGIN TRY
		IF @IdReport IS NOT NULL --Por Id
			BEGIN
				SELECT * FROM dbo.Reports WITH (NOLOCK)
					WHERE IdReport = @IdReport
			END
		ELSE IF @IdReport IS NULL AND @StatusReport IS NULL --Todos
			BEGIN
				SELECT * FROM dbo.Reports WITH (NOLOCK)
			END
	END TRY
	BEGIN CATCH
	SELECT ERROR_MESSAGE() AS ERROR,
				ERROR_NUMBER() AS ERROR_NRO
	END CATCH;
END
GO